create table users (
   username          varchar(50) not null primary key,
   name              varchar(50) not null,
   surname           varchar(50) not null,
   email             varchar(100) not null unique,
   password          varchar(100) not null,
   weight            numeric(5,2),
   height            numeric(5,2),
   verified          integer default 0,
   favorite_exercise integer,
   avatar            varchar(7)
);

create table workouts (
   workout_id       integer
      generated by default as identity
   primary key,
   start_datetime   timestamp,
   username         varchar(50) not null,
   end_datetime     timestamp,
   description      varchar(255),
   created_datetime timestamp default current_timestamp,
   is_posted        integer default 0,
   schedule         integer default 0,
   constraint fk_workouts_username foreign key ( username )
      references users ( username )
         on delete cascade
);

create table muscles (
   muscle_id   integer not null primary key,
   muscle_name varchar(40) not null
);

create table exercises (
   exercise_id integer
      generated by default as identity
   primary key,
   type        char(1) default 'strength',
   kcal_burned integer default 0,
   name        varchar(40) not null,
   video_id    varchar(11)
);

create table exercises_muscles (
   id          integer
      generated by default as identity
   primary key,
   exercise_id integer not null,
   muscle_id   integer not null,
   constraint muscle_fk foreign key ( muscle_id )
      references muscles ( muscle_id ),
   constraint exercise_fk foreign key ( exercise_id )
      references exercises ( exercise_id )
         on delete cascade
);

create table activities (
   activity_id integer
      generated by default as identity
   primary key,
   exercise_id integer not null,
   reps        integer,
   weight      integer,
   duration    varchar(40),
   workout_id  integer not null,
   constraint fk_workout foreign key ( workout_id )
      references workouts ( workout_id )
         on delete cascade,
   constraint fk_exercise foreign key ( exercise_id )
      references exercises ( exercise_id )
         on delete cascade
);

create table token (
   email              varchar(255) not null primary key,
   verification_token varchar(255),
   reset_token        varchar(255),
   reset_expiry       timestamp,
   constraint email_fk foreign key ( email )
      references users ( email )
         on delete cascade
);

create table friendships (
   id               integer
      generated by default as identity
   primary key,
   friend1_username varchar(50) not null,
   friend2_username varchar(50) not null,
   created_at       timestamp default current_timestamp,
   constraint friendship_unique_pair1 unique ( friend1_username,
                                               friend2_username ),
   constraint fk_user1 foreign key ( friend1_username )
      references users ( username )
         on delete cascade,
   constraint fk_user2 foreign key ( friend2_username )
      references users ( username )
         on delete cascade
);

create table friendship_invitations (
   id                   integer
      generated by default as identity
   primary key,
   who_send_username    varchar(50) not null,
   who_receive_username varchar(50) not null,
   send_time            timestamp default current_timestamp,
   constraint unique_friendship_invitation unique ( who_send_username,
                                                    who_receive_username ),
   constraint fk_who_receive foreign key ( who_receive_username )
      references users ( username )
         on delete cascade,
   constraint fk_who_send foreign key ( who_send_username )
      references users ( username )
         on delete cascade
);

create table posts (
   post_id         integer
      generated always as identity
   primary key,
   author_username varchar(50) not null,
   post_date       timestamp default current_timestamp,
   title           varchar(100) not null,
   workout_id      integer,
   content         varchar(200),
   constraint fk_username foreign key ( author_username )
      references users ( username )
         on delete cascade,
   constraint fk_workout_id foreign key ( workout_id )
      references workouts ( workout_id )
         on delete cascade
);

create table post_comments (
   post_comment_id   integer
      generated always as identity
   primary key,
   post_id           integer not null,
   author_username   varchar(50) not null,
   content           varchar(255),
   post_comment_date timestamp default current_timestamp,
   constraint fk_post_id foreign key ( post_id )
      references posts ( post_id ),
   constraint fk_author_username foreign key ( author_username )
      references users ( username )
);

create table post_reactions (
   post_reaction_id integer
      generated always as identity
   primary key,
   post_id          integer not null,
   author_username  varchar(40) not null,
   constraint unique_reaction_author unique ( post_id,
                                              author_username ),
   constraint fk_reactor_username foreign key ( author_username )
      references users ( username )
         on delete cascade,
   constraint fk_reaction_post_id foreign key ( post_id )
      references posts ( post_id )
         on delete cascade
);