Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell bench press', 'EeE3f4VWFDo');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell bench press', 'YQ2s_Y7g5Qk');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell shoulder press', 'EeE3f4VWFDo');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell shoulder press', 'HzIiNhHhhtA');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell lateral raise', 'OuG1smZTsQQ');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell chest fly', 'JFm8KbhjibM');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dip', '4LA1kF7yCGo');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'cable tricep pushdown', '6Fzep104f0s');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell frontal raise', 'hRJ6tR5-if0');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell skull crushers', 'jPjhQ2hsAds');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine chest press', 'NwzUje3z0qY');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine shoulder press', 'WvLMauqrnK8');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine lateral raise', '0o07iGKUarI');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine tricep extension', 'Bx8ga1BLHLE');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'push up', 'mm6_WcoCVTA');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'incline barbell bench press', 'lJ2o89kcnxY');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'incline dumbbell bench press', '5CECBjd7HLQ');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'decline barbell bench press', 'UH3w618WAAc');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'decline dumbbell bench press', '4R_GwRhG0rY');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine chest fly', 'FDay9wFe5uE');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell bicep curl', 'JnLFSFurrqQ');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell bicep  curl', 'iixND1P2lik');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'bicep hammer curl', 'XOEL4MgekYE');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine bicep curl', 'Ja6ZlIDONac');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine bicep hammer curl', 'Ja6ZlIDONac');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell row', '6FZHJGzMFEc');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell row', 'DMo3HJoawrU');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'cable row', 'UCXxvVItLoM');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'pull up', 'GRgWPT9XSQQ');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'cable face pull', '-MODnZdnmAQ');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'chin up', '9JC1EwqezGY');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell wrist curl', '2wPpcJBe03o');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell wrist curl', 'lfQR7oVS8eo');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell wrist extension', 'la-0c4ubkvs');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell wrist extension', 'PMdkUNXrB9Q');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell reverse curl', 'TUX58GM5fRQ');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell reverse curl', 'hUA-fIpM7nA');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'back extension', '5_ejbGfdAQE');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell squat', 'i7J5h7BJ07g');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine leg press', 'yZmx_Ac3880');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine horizontal leg press', 'ccTiGvrsUUY');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'hack squat', 'rYgNArpwE7E');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine leg extension', 'm0FOpMEgero');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine leg curl', 'Orxowest56U');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell standing calf raises', 'hh5516HCu4k');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine calf raises', 'N3awlEyTY98');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell lunges', 'eFWCn5iEbTU');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell lunges', '_meXEWq5MOQ');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'hip thrust', 'EF7jXP17DPE');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell bulgarian split squat', 'jNihW0WDIL4');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'barbell front squat', 'HHxNbhP16UE');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'deadlift', 'AweC3UaM14o');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'romanian deadlift', 'bT5OOBgY4bc');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'sumo deadlift', 'pfSMst14EFk');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 0, 'farmer walk', 'dX0itH_wXBQ');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'shrugs', '_t3lrPI6Ns4');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'sit ups', 'pXg8qppif7I');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'decline sit ups', 'DAnTf16NcT0');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'crunches', '0t4t3IpiEao');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'decline crunches', 'dVO_yOfvp3A');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'russian twists', 'pzMWYoeSCzw');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'neck curl', 'WSfy5wpU_Io');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'neck extensions', 'Z6rZ8oRyFAk');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine reverse fly', '5YK4bgzXDp0');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell reverse fly', 'hf7jnF45N_I');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 2, 'plank', 'EPiXN2bkLoQ');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'leg raises', 'q0JVBRHoLz4');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 5, 'walking', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 10, 'jogging', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 15, 'running', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 20, 'sprinting', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 12, 'swimming', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 10, 'cycling', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 8, 'jumping jacks', 'uLVt6u15L98');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine leg abduction', 'G_8LItOiZ0Q');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine leg adduction', 'CjAVezAggkI');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'machine lat pulldown', 'EUIri47Epcg');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 8, 'incline walking', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 10, 'trap bar farmer''s walk', 'ivqzKhwOpvI');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 12, 'stepper', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 18, 'burpees', 'TU8QYVW0gDU');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('C', 14, 'rope skipping', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 10, 'dumbbell farmer''s walk', '8OtwXwrJizk');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 12, 'battle ropes alternating waves', 'ZujykKeVZpM');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 12, 'battle ropes side waves', 'tDCgANYoO3Q');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 12, 'battle ropes inside circles', 'ycYOpuuqnLw');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 12, 'battle ropes outside circles', 'bIeB-Ut8YJM');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 10, 'battle ropes uppercuts', 'HIZI3TkbJjs');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 20, 'battle ropes jumping jacks', 'r7Ndi0YYZ-0');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 14, 'battle ropes slams', '7wDx6mZDxA8');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 100, 'kidmaker', 'I-u4F-E5yJ0');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('S', 0, 'dumbbell bulgarian split squat', 'Fmjj7wFJWRE');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 10, 'weighted wall sit', '8e42dL8MeMw');
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 12, 'rowing', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 14, 'weighted running', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 10, 'weighted walking', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 11, 'weighted incline walking', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 12, 'weighted jumping jacks', null);
Insert into EXERCISES (TYPE, KCAL_BURNED, NAME, VIDEO_ID) VALUES ('F', 10, 'weighted rope skipping', null);