-- --- INSERTING into ACTIVITIES

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 309,
--            7,
--            12,
--            12,
--            null,
--            97 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 304,
--            7,
--            123,
--            132,
--            null,
--            90 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 247,
--            73,
--            null,
--            null,
--            interval '2 hours',
--            70 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 248,
--            72,
--            null,
--            null,
--            interval '1 hour',
--            70 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 249,
--            20,
--            40,
--            60,
--            null,
--            70 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 250,
--            14,
--            30,
--            40,
--            null,
--            70 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 251,
--            39,
--            30,
--            20,
--            null,
--            70 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 252,
--            54,
--            20,
--            200,
--            null,
--            71 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 253,
--            261,
--            0,
--            50,
--            interval '10 minutes',
--            71 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 254,
--            262,
--            0,
--            100,
--            interval '30 minutes',
--            72 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 255,
--            1,
--            12,
--            60,
--            null,
--            72 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 256,
--            1,
--            12,
--            60,
--            null,
--            72 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 257,
--            1,
--            12,
--            60,
--            null,
--            72 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 258,
--            8,
--            10,
--            50,
--            null,
--            72 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 259,
--            8,
--            10,
--            55,
--            null,
--            72 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 260,
--            6,
--            12,
--            40,
--            null,
--            2 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 261,
--            64,
--            15,
--            50,
--            null,
--            6 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 310,
--            66,
--            null,
--            null,
--            interval '12 hours',
--            97 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 302,
--            73,
--            null,
--            null,
--            interval '12 hours',
--            82 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 307,
--            7,
--            12,
--            12,
--            null,
--            96 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 265,
--            21,
--            20,
--            40,
--            null,
--            71 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 266,
--            21,
--            16,
--            40,
--            null,
--            71 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 267,
--            21,
--            12,
--            40,
--            null,
--            71 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 268,
--            21,
--            8,
--            40,
--            null,
--            71 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 269,
--            21,
--            5,
--            40,
--            null,
--            71 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 270,
--            23,
--            12,
--            15,
--            null,
--            71 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 271,
--            23,
--            10,
--            15,
--            null,
--            71 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 308,
--            66,
--            null,
--            null,
--            interval '12 hours',
--            96 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 311,
--            66,
--            null,
--            null,
--            interval '12 hours',
--            98 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 312,
--            173,
--            0,
--            234234,
--            interval '12 hours 30 minutes 10 seconds',
--            98 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 31,
--            21,
--            20,
--            40,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 32,
--            21,
--            16,
--            40,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 33,
--            21,
--            12,
--            40,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 34,
--            21,
--            8,
--            40,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 35,
--            21,
--            5,
--            40,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 36,
--            23,
--            12,
--            15,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 37,
--            23,
--            10,
--            15,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 38,
--            23,
--            8,
--            15,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 39,
--            29,
--            11,
--            0,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 40,
--            29,
--            8,
--            0,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 41,
--            29,
--            2,
--            15,
--            null,
--            3 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 313,
--            1,
--            123,
--            24342,
--            null,
--            54 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 234,
--            73,
--            null,
--            null,
--            interval '12 hours',
--            54 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 314,
--            173,
--            0,
--            234,
--            interval '12 hours 30 minutes 10 seconds',
--            54 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 196,
--            66,
--            null,
--            null,
--            interval '4 hours 10 minutes 45 seconds',
--            48 );

-- insert into activities (
--    activity_id,
--    exercise_id,
--    reps,
--    weight,
--    duration,
--    workout_id
-- ) values ( 243,
--            168,
--            null,
--            null,
--            interval '12 hours 30 minutes 10 seconds',
--            68 );